**타이타닉 데이터 분석 및 피쳐 확인하기**
survived 추론을 목표로 각 테이블이 예측에 필요한지 검토

*   머신러닝 모델의 성능은 어떤 데이터를 학습시키느냐에 달려 있다.

-------------------


데이터의 각 테이블 분석

In [1]:
# 데이터 관리 도구
import pandas as pd  #
import numpy as np   #

# 데이터 전처리 도구
from sklearn.model_selection import train_test_split # 데이터를 학습용/검증용으로 나눔
from sklearn.preprocessing import LabelEncoder      # 문자를 숫자로 바꿈
from sklearn.preprocessing import StandardScaler    # 숫자의 크기(Scale)를 일정하게 맞춤

# AI 모델(알고리즘) 도구
from sklearn.linear_model import LogisticRegression  # 선형 분류(LR)
from sklearn.tree import DecisionTreeClassifier       # 의사결정나무(DT)
from sklearn.ensemble import RandomForestClassifier  # 랜덤 포레스트(RF)
from sklearn.neighbors import KNeighborsClassifier   # K-최근접 이웃(KNN)

# 성능 점수판 도구
from sklearn.metrics import accuracy_score #정답의 정확도를 계산

In [ ]:
#df.drop([...])	불필요한 정보 제거
#fillna()	빈칸 채우기
#le.fit_transform()	라벨 인코딩
#StandardScaler()	데이터 표준화

In [15]:
# 1. 데이터 로드
path = "/content/drive/MyDrive/가천대학교/2026-1/인공지능개론/Colab Notebooks/2. 데이터/titanic.csv"
df = pd.read_csv(path)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
# 2. 필요 없는 칼럼 제거
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, errors='ignore')
df
# 'ignore' 칼럼이 없을 경우 pass 한다! 중복 실행으로 인한 오류 해결

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000         2
887         1       1    0  19.0      0      0  30.0000         2
888         0       3    0  28.0      1      2  23.4500         2
889         1       1    1  26.0      0      0  30.0000         0
890         0       3    1  32.0      0      0   7.7500         1

[891 rows x 8 columns]

In [25]:
# 3. 결측치(NaN, Null) 처리
df['Age'] = df['Age'].fillna(df['Age'].median()) # 나이는 중앙값 채움
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0]) # 항구는 최빈값을 채움
df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000         2
887         1       1    0  19.0      0      0  30.0000         2
888         0       3    0  28.0      1      2  23.4500         2
889         1       1    1  26.0      0      0  30.0000         0
890         0       3    1  32.0      0      0   7.7500         1

[891 rows x 8 columns]

In [28]:
# 4. Label Encoding (글자 -> 숫자 변경)
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex']) # male:1, female:0 (반대로도 ok)
df['Embarked'] = le.fit_transform(df['Embarked'])
df
#

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000         2
887         1       1    0  19.0      0      0  30.0000         2
888         0       3    0  28.0      1      2  23.4500         2
889         1       1    1  26.0      0      0  30.0000         0
890         0       3    1  32.0      0      0   7.7500         1

[891 rows x 8 columns]

In [31]:
# 5. x, y로 (특징과 정답) 분리
X = df.drop('Survived', axis=1)
y = df['Survived']
X, y

(     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
 0         3    1  22.0      1      0   7.2500         2
 1         1    0  38.0      1      0  71.2833         0
 2         3    0  26.0      0      0   7.9250         2
 3         1    0  35.0      1      0  53.1000         2
 4         3    1  35.0      0      0   8.0500         2
 ..      ...  ...   ...    ...    ...      ...       ...
 886       2    1  27.0      0      0  13.0000         2
 887       1    0  19.0      0      0  30.0000         2
 888       3    0  28.0      1      2  23.4500         2
 889       1    1  26.0      0      0  30.0000         0
 890       3    1  32.0      0      0   7.7500         1

 [891 rows x 7 columns],
 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 886    0
 887    1
 888    0
 889    1
 890    0
 Name: Survived, Length: 891, dtype: int64)

In [30]:
# 6. 데이터 스케일링(KNN에 맞추기)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [33]:
# 6. 학습(8:2)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=0)

In [43]:
# 모델 생성
models = [LogisticRegression(), DecisionTreeClassifier(), RandomForestClassifier(), KNeighborsClassifier()]

# 학습 및 결과 출력(for문으로 통합)
for model in models:
    model.fit(X_train, y_train)
    name = model.__class__.__name__ # class의 name 담기
    print(f"{name} 모델의 결과: {accuracy_score(y_test, model.predict(X_test))}")

LogisticRegression 모델의 결과: 0.7937219730941704
DecisionTreeClassifier 모델의 결과: 0.7668161434977578
RandomForestClassifier 모델의 결과: 0.8251121076233184
KNeighborsClassifier 모델의 결과: 0.8116591928251121

In [45]:
# 7. 모델의 정확도와 사망확률은 다르다 -> 확률로 도출
for model in models:
    # 1. 모델 학습
    model.fit(X_train, y_train)

    # 2. 모델 이름 가져오기
    name = model.__class__.__name__

    # 3. 정확도(성적표) 계산
    acc = accuracy_score(y_test, model.predict(X_test))

    # 4. 개별 승객의 '확률' 계산 (중요!)
    # predict_proba는 [사망확률, 생존확률] 두 값을 줍니다.
    probs = model.predict_proba(X_test)

    # 결과 출력
    print(f"[{name}]")
    print(f"- 전체 정확도: {acc:.4f}")
    # probs[0][0]은 첫 번째 승객의 사망 확률, probs[0][1]은 생존 확률입니다.
    print(f"- 첫 번째 승객 확률: [사망 {probs[0][0]:.2%}, 생존 {probs[0][1]:.2%}]")
    print("-" * 30)

[LogisticRegression]
- 전체 정확도: 0.7937
- 첫 번째 승객 확률: [사망 84.15%, 생존 15.85%]
------------------------------
[DecisionTreeClassifier]
- 전체 정확도: 0.7623
- 첫 번째 승객 확률: [사망 100.00%, 생존 0.00%]
------------------------------
[RandomForestClassifier]
- 전체 정확도: 0.8341
- 첫 번째 승객 확률: [사망 76.75%, 생존 23.25%]
------------------------------
[KNeighborsClassifier]
- 전체 정확도: 0.8117
- 첫 번째 승객 확률: [사망 100.00%, 생존 0.00%]
------------------------------